# Uygulama Ayarlar?
server.port=9000
server.servlet.context-path=/workintech

# Veritaban? Ba?lant?s? (PostgreSQL - postgres DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=hello

# Hibernate & JPA Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# SQL Loglar?n? Detayl? Görmek ?çin (Görev 1 uyar?nca)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Türkçe Karakter Sorunu Ya?amamak ?çin (Opsiyonel)
spring.datasource.sql-script-encoding=UTF-8